config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get '/about', to: "pages#about"
  resources :articles
  get 'signup', to: "users#new"
  resources :users, except: [:new] #all routes the new user routes as signup
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base 
    belongs_to :user 

    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
    validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles
    before_save { self.email = email.downcase}


    validates :username, presence: true,
               uniqueness: {case_sensitive: false}, 
               length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 105}, 
               uniqueness: {case_sensitive: false},
    format: {with: VALID_EMAIL_REGEX }

    has_secure_password
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]

    def index 
        @articles = Article.all
    end

    def new 
        @article = Article.new
    end
    
    def edit
    end

    def create 
        debugger
        @article = Article.new(article_params)
        @article.user = User.first
        if @article.save #show path is article_path
            flash[:notice] = "Article was successfully created"
            redirect_to article_path(@article)
        else  #validations that fail so renders new template again
            render 'new'
        end 
    end

    def update 
      if @article.update(article_params) 
        #reuse article_params to whitelist whatever has been submitted
        flash[:notice] = "Article was successfully updated"
        redirect_to article_path(@article)
      else 
        render :edit 
      end 
    end

    def show 
    end

    def destroy 
        @article.destroy 
        flash[:notice] = "Article was successfully deleted"
        redirect_to articles_path
    end

    private 
    def set_article
        @article = Article.find(params[:id])
    end
    def article_params
        params.require(:article).permit(:title, :description)
    end

    

    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home 
    end
    def about

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new 
    @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save 
            flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
            redirect_to articles_path
        else
            render "new"
        end

    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:success] = "Your account was updated successfully"
            redirect_to articles_path
        else 
            render "edit"
        end
    end

    def show 
        @user = User.find(params[:id])
    end
    
    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2> The following errors prevented the article from getting created </h2>
<ul>
<% @article.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>

<%= form_for(@article) do |f| %>
<p>
<%= f.label :title %> <br>
<%= f.text_field :title %>
</p>

<p>
<%= f.label :description %><br>
<%= f.text_area :description %>
</p>
<%= f.submit %>
<% end %>

<%= link_to "Back to articles listing", articles_path %>

<% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %>prohibited this article from being saved: </h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit existing article </h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing all articles </h1>
<p>
<%= link_to "Create new article", new_article_path %>
</p>
<table>
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Created by: </th>
    </tr>

    <% @articles.each do |article| %>
    <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td> <%= article.user.username %>, <%= time_ago_in_words(article.created_at) %> ago, 
        last updated: <%= time_ago_in_words(article.updated_at) %> ago </td>
        <td><%= link_to "Edit", edit_article_path(article) %></td>
        <td><%= link_to "Show", article_path(article) %></td>
        <td> <%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
    <% end %>

</table>

app/views/articles/new.html.erb
<h1>Create an article </h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>

<p>Title: <%= @article.title %></p>
<p> Description: <%= @article.description %></p><br>

<%= link_to "Edit this article", edit_article_path(@article) %> |
<%= link_to "Back to articles listing", articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<ul>
    <li><%= msg %></li>
    </ul>
<%end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render '/layouts/messages' %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>
 

app/views/pages/about.html.erb
<h1> About page</h1>

<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<h1>This is the home page of my blog app</h1>

<%= link_to "Alpa Blog", articles_path %> | <%= link_to "About", about_path %>
    



    

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<h2> The following errors prevented the user from getting created </h2>
<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>

<%= form_for(@user) do |f| %>
<p>
<%= f.label :username %> <br>
<%= f.text_field :username%>
</p>

<p>
<%= f.label :email %><br>
<%= f.email_field :email %>
</p>

<p>
<%= f.label :password %><br>
<%= f.password_field :password %>
</p>
<%= f.submit(@user.new_record? ? "Sign up" : "Update account") %>
<% end %>

<%= link_to "Back to articles listing", articles_path %>

app/views/users/edit.html.erb
<h1 align='center'>Edit your account </h1>
<%= render "form" %>

app/views/users/new.html.erb
<h1 align= 'center'> Sign up for Alpha Blog </h1>
<%= render "form" %>